### ISSUE TITLE
The display name should follow the format: [Company Name] [Tag Name]

### ISSUE THREAD

**Issue by opozo** [stape-io/facebook-leads-tag#2]
The current display name is as follows:

Display Name: Facebook Leads Tag

The display name should follow the format: [Company Name] [Tag Name].

**Comment by Bukashk0zzz** [comment]
Thanks.

Fixed in https://github.com/stape-io/facebook-leads-tag/commit/bdd6e0fcda93b312ba1a921753f20792d97ab568
