### ISSUE TITLE
Use encodeUri() if part of the URL path

### ISSUE THREAD

**Issue by opozo** [stape-io/facebook-leads-tag#4]
When reviewing your template we've noticed that it is using user-defined parameters to build a URL. It's best practice to use [encodeUri()](https://developers.google.com/tag-manager/templates/api#encodeuri) if part of the URL path [[1](https://github.com/stape-io/facebook-leads-tag/blob/a4cea1642c49776cf5aaa8caff34f198c3ca9e22/template.tpl#L153)].

**Comment by Bukashk0zzz** [comment]
Thanks.

Fixed in https://github.com/stape-io/facebook-leads-tag/commit/bdd6e0fcda93b312ba1a921753f20792d97ab568
